package govin

var (
	manufacturers = []WMIManufacturer{
		WMIManufacturer{"AFA", "Ford South Africa"},
		WMIManufacturer{"AAV", "Volkswagen South Africa"},
		WMIManufacturer{"JA3", "Mitsubishi"},
		WMIManufacturer{"JA", "Isuzu"},
		WMIManufacturer{"JF", "Fuji Heavy Industries (Subaru)"},
		WMIManufacturer{"JHM", "Honda"},
		WMIManufacturer{"JHG", "Honda"},
		WMIManufacturer{"JHL", "Honda"},
		WMIManufacturer{"JK", "Kawasaki (motorcycles)"},
		WMIManufacturer{"JM", "Mazda"},
		WMIManufacturer{"JN", "Nissan"},
		WMIManufacturer{"JS", "Suzuki"},
		WMIManufacturer{"JT", "Toyota"},
		WMIManufacturer{"KL", "Daewoo General Motors South Korea"},
		WMIManufacturer{"KM8", "Hyundai"},
		WMIManufacturer{"KMH", "Hyundai"},
		WMIManufacturer{"KNA", "Kia"},
		WMIManufacturer{"KNB", "Kia"},
		WMIManufacturer{"KNC", "Kia"},
		WMIManufacturer{"KNM", "Renault Samsung"},
		WMIManufacturer{"KPA", "Ssangyong"},
		WMIManufacturer{"KPT", "Ssangyong"},
		WMIManufacturer{"L56", "Renault Samsung"},
		WMIManufacturer{"L5Y", "Merato Motorcycle Taizhou Zhongneng"},
		WMIManufacturer{"LDY", "Zhongtong Coach (China)"},
		WMIManufacturer{"LGH", "Dong Feng (DFM - China)"},
		WMIManufacturer{"LKL", "Suzhou King Long (China)"},
		WMIManufacturer{"LSY", "Brilliance Zhonghua"},
		WMIManufacturer{"LTV", "Toyota Tian Jin"},
		WMIManufacturer{"LVS", "Ford Chang An"},
		WMIManufacturer{"LVV", "Chery (China"},
		WMIManufacturer{"LZM", "MAN China"},
		WMIManufacturer{"LZE", "Isuzu Guangzhou (China)"},
		WMIManufacturer{"LZG", "Shaanxi Automobile Group (China)"},
		WMIManufacturer{"LZY", "Yutong Zhengzhou (China)"},
		WMIManufacturer{"MA1", "Mahindra"},
		WMIManufacturer{"MA3", "Suzuki India"},
		WMIManufacturer{"MA7", "Honda Siel Cars India"},
		WMIManufacturer{"MAL", "Hyundai"},
		WMIManufacturer{"MHR", "Honda Indonesia"},
		WMIManufacturer{"MNB", "Ford Thailand"},
		WMIManufacturer{"MNT", "Nissan Thailand"},
		WMIManufacturer{"MMB", "Mitsubishi Thailand"},
		WMIManufacturer{"MMM", "Chevrolet Thailand"},
		WMIManufacturer{"MMT", "Mitsubishi Thailand"},
		WMIManufacturer{"MM8", "Mazda Thailand"},
		WMIManufacturer{"MPA", "Isuzu Thailand"},
		WMIManufacturer{"MP1", "Isuzu Thailand"},
		WMIManufacturer{"MRH", "Honda Thailand"},
		WMIManufacturer{"MR0", "Toyota Thailand"},
		WMIManufacturer{"NLE", "Mercedes-Benz Turk Truck"},
		WMIManufacturer{"NM0", "Ford Turkey"},
		WMIManufacturer{"NM4", "Tofas Turk"},
		WMIManufacturer{"NMT", "Toyota Turkiye"},
		WMIManufacturer{"PE1", "Ford Phillipines"},
		WMIManufacturer{"PE3", "Mazda Phillipines"},
		WMIManufacturer{"PL1", "Proton (Malaysia)"},
		WMIManufacturer{"SAL", "Land Rover"},
		WMIManufacturer{"SAJ", "Jaguar"},
		WMIManufacturer{"SAR", "Rover"},
		WMIManufacturer{"SCA", "Rolls Royce"},
		WMIManufacturer{"SCC", "Lotus Cars"},
		WMIManufacturer{"SCE", "DeLorean Motor Cars N. Ireland (UK)"},
		WMIManufacturer{"SCF", "Aston"},
		WMIManufacturer{"SDB", "Peugeot UK"},
		WMIManufacturer{"SFD", "Alexander Dennis UK"},
		WMIManufacturer{"SHS", "Honda UK"},
		WMIManufacturer{"SJN", "Nissan UK"},
		WMIManufacturer{"SU9", "Solaris Bus & Coach (Poland)"},
		WMIManufacturer{"TK9", "SOR (Czech Republic)"},
		WMIManufacturer{"TDM", "QUANTYA Swiss Electric Movement (Switzerland)"},
		WMIManufacturer{"TMB", "Škoda (Czech Republic)"},
		WMIManufacturer{"TMK", "Karosa (Czech Republic)"},
		WMIManufacturer{"TMP", "Škoda trolleybuses (Czech Republic)"},
		WMIManufacturer{"TMT", "Tatra (Czech Republic)"},
		WMIManufacturer{"TM9", "Škoda trolleybuses (Czech Republic)"},
		WMIManufacturer{"TN9", "Karosa (Czech Republic)"},
		WMIManufacturer{"TRA", "Ikarus Bus"},
		WMIManufacturer{"TRU", "Audi Hungary"},
		WMIManufacturer{"TSE", "Ikarus Egyedi Autobuszgyar (Hungary)"},
		WMIManufacturer{"TSM", "Suzuki (Hungary)"},
		WMIManufacturer{"UU1", "Renault Dacia (Romania)"},
		WMIManufacturer{"VF1", "Renault"},
		WMIManufacturer{"VF3", "Peugeot"},
		WMIManufacturer{"VF6", "Renault (Trucks & Buses)"},
		WMIManufacturer{"VF7", "Citroën"},
		WMIManufacturer{"VF8", "Matra"},
		WMIManufacturer{"VLU", "Scania France"},
		WMIManufacturer{"VNE", "Irisbus (France)"},
		WMIManufacturer{"VSE", "Suzuki Spain (Santana Motors)"},
		WMIManufacturer{"VSK", "Nissan Spain"},
		WMIManufacturer{"VSS", "SEAT"},
		WMIManufacturer{"VSX", "Opel Spain"},
		WMIManufacturer{"VS6", "Ford Spain"},
		WMIManufacturer{"VS9", "Carrocerias Ayats (Spain)"},
		WMIManufacturer{"VV9", "TAUROSpain"},
		WMIManufacturer{"VWV", "Volkswagen Spain"},
		WMIManufacturer{"VX1", "Zastava / Yugo Serbia"},
		WMIManufacturer{"WAG", "Neoplan"},
		WMIManufacturer{"WAU", "Audi"},
		WMIManufacturer{"WBA", "BMW"},
		WMIManufacturer{"WBS", "BMW M"},
		WMIManufacturer{"WDB", "Mercedes-Benz"},
		WMIManufacturer{"WDC", "DaimlerChrysler"},
		WMIManufacturer{"WDD", "McLaren"},
		WMIManufacturer{"WEB", "Evobus GmbH (Mercedes-Bus)"},
		WMIManufacturer{"WF0", "Ford Germany"},
		WMIManufacturer{"WMA", "MAN Germany"},
		WMIManufacturer{"WMW", "MINI"},
		WMIManufacturer{"WP0", "Porsche"},
		WMIManufacturer{"W0L", "Opel"},
		WMIManufacturer{"WVW", "Volkswagen"},
		WMIManufacturer{"WV1", "Volkswagen Commercial Vehicles"},
		WMIManufacturer{"WV2", "Volkswagen Bus/Van"},
		WMIManufacturer{"XL9", "Spyker"},
		WMIManufacturer{"XMC", "Mitsubishi (NedCar)"},
		WMIManufacturer{"XTA", "Lada/AutoVaz (Russia)"},
		WMIManufacturer{"YK1", "Saab"},
		WMIManufacturer{"YS2", "Scania AB"},
		WMIManufacturer{"YS3", "Saab"},
		WMIManufacturer{"YS4", "Scania Bus"},
		WMIManufacturer{"YV1", "Volvo Cars"},
		WMIManufacturer{"YV4", "Volvo Cars"},
		WMIManufacturer{"YV2", "Volvo Trucks"},
		WMIManufacturer{"YV3", "Volvo Buses"},
		WMIManufacturer{"ZAM", "Maserati Biturbo"},
		WMIManufacturer{"ZAP", "Piaggio/Vespa/Gilera"},
		WMIManufacturer{"ZAR", "Alfa Romeo"},
		WMIManufacturer{"ZCG", "Cagiva SpA"},
		WMIManufacturer{"ZDM", "Ducati Motor Holdings SpA"},
		WMIManufacturer{"ZDF", "Ferrari Dino"},
		WMIManufacturer{"ZD4", "Aprilia"},
		WMIManufacturer{"ZFA", "Fiat"},
		WMIManufacturer{"ZFC", "Fiat V.I."},
		WMIManufacturer{"ZFF", "Ferrari"},
		WMIManufacturer{"ZHW", "Lamborghini"},
		WMIManufacturer{"ZLA", "Lancia"},
		WMIManufacturer{"ZOM", "OM"},
		WMIManufacturer{"1C3", "Chrysler"},
		WMIManufacturer{"1C6", "Chrysler"},
		WMIManufacturer{"1D3", "Dodge"},
		WMIManufacturer{"1FA", "Ford Motor Company"},
		WMIManufacturer{"1FB", "Ford Motor Company"},
		WMIManufacturer{"1FC", "Ford Motor Company"},
		WMIManufacturer{"1FD", "Ford Motor Company"},
		WMIManufacturer{"1FM", "Ford Motor Company"},
		WMIManufacturer{"1FT", "Ford Motor Company"},
		WMIManufacturer{"1FU", "Freightliner"},
		WMIManufacturer{"1FV", "Freightliner"},
		WMIManufacturer{"1F9", "FWD Corp."},
		WMIManufacturer{"1G", "General Motors USA"},
		WMIManufacturer{"1GC", "Chevrolet Truck USA"},
		WMIManufacturer{"1GT", "GMC Truck USA"},
		WMIManufacturer{"1G1", "Chevrolet USA"},
		WMIManufacturer{"1G2", "Pontiac USA"},
		WMIManufacturer{"1G3", "Oldsmobile USA"},
		WMIManufacturer{"1G4", "Buick USA"},
		WMIManufacturer{"1G6", "Cadillac USA"},
		WMIManufacturer{"1GM", "Pontiac USA"},
		WMIManufacturer{"1G8", "Saturn USA"},
		WMIManufacturer{"1H", "Honda USA"},
		WMIManufacturer{"1HD", "Harley-Davidson"},
		WMIManufacturer{"1J4", "Jeep"},
		WMIManufacturer{"1L", "Lincoln USA"},
		WMIManufacturer{"1ME", "Mercury USA"},
		WMIManufacturer{"1M1", "Mack Truck USA"},
		WMIManufacturer{"1M2", "Mack Truck USA"},
		WMIManufacturer{"1M3", "Mack Truck USA"},
		WMIManufacturer{"1M4", "Mack Truck USA"},
		WMIManufacturer{"1N", "Nissan USA"},
		WMIManufacturer{"1NX", "NUMMI USA"},
		WMIManufacturer{"1P3", "Plymouth USA"},
		WMIManufacturer{"1R9", "Roadrunner Hay Squeeze USA"},
		WMIManufacturer{"1VW", "Volkswagen USA"},
		WMIManufacturer{"1XK", "Kenworth USA"},
		WMIManufacturer{"1XP", "Peterbilt USA"},
		WMIManufacturer{"1YV", "Mazda USA (AutoAlliance International)"},
		WMIManufacturer{"2C3", "Chrysler Canada"},
		WMIManufacturer{"2CN", "CAMI"},
		WMIManufacturer{"2D3", "Dodge Canada"},
		WMIManufacturer{"2FA", "Ford Motor Company Canada"},
		WMIManufacturer{"2FB", "Ford Motor Company Canada"},
		WMIManufacturer{"2FC", "Ford Motor Company Canada"},
		WMIManufacturer{"2FM", "Ford Motor Company Canada"},
		WMIManufacturer{"2FT", "Ford Motor Company Canada"},
		WMIManufacturer{"2FU", "Freightliner"},
		WMIManufacturer{"2FV", "Freightliner"},
		WMIManufacturer{"2FZ", "Sterling"},
		WMIManufacturer{"2G", "General Motors Canada"},
		WMIManufacturer{"2G1", "Chevrolet Canada"},
		WMIManufacturer{"2G2", "Pontiac Canada"},
		WMIManufacturer{"2G3", "Oldsmobile Canada"},
		WMIManufacturer{"2G4", "Buick Canada"},
		WMIManufacturer{"2HG", "Honda Canada"},
		WMIManufacturer{"2HK", "Honda Canada"},
		WMIManufacturer{"2HM", "Hyundai Canada"},
		WMIManufacturer{"2M", "Mercury"},
		WMIManufacturer{"2NV", "Nova Bus Canada"},
		WMIManufacturer{"2P3", "Plymouth Canada"},
		WMIManufacturer{"2T", "Toyota Canada"},
		WMIManufacturer{"2V4", "Volkswagen Canada"},
		WMIManufacturer{"2WK", "Western Star"},
		WMIManufacturer{"2WL", "Western Star"},
		WMIManufacturer{"2WM", "Western Star"},
		WMIManufacturer{"3D3", "Dodge Mexico"},
		WMIManufacturer{"3FA", "Ford Motor Company Mexico"},
		WMIManufacturer{"3FE", "Ford Motor Company Mexico"},
		WMIManufacturer{"3G", "General Motors Mexico"},
		WMIManufacturer{"3H", "Honda Mexico"},
		WMIManufacturer{"3N", "Nissan Mexico"},
		WMIManufacturer{"3P3", "Plymouth Mexico"},
		WMIManufacturer{"3VW", "Volkswagen Mexico"},
		WMIManufacturer{"4F", "Mazda USA"},
		WMIManufacturer{"4M", "Mercury"},
		WMIManufacturer{"4RK", "Nova Bus USA"},
		WMIManufacturer{"4S", "Subaru-Isuzu Automotive"},
		WMIManufacturer{"4T", "Toyota"},
		WMIManufacturer{"4US", "BMW USA"},
		WMIManufacturer{"4UZ", "Frt-Thomas Bus"},
		WMIManufacturer{"4V1", "Volvo"},
		WMIManufacturer{"4V2", "Volvo"},
		WMIManufacturer{"4V3", "Volvo"},
		WMIManufacturer{"4V4", "Volvo"},
		WMIManufacturer{"4V5", "Volvo"},
		WMIManufacturer{"4V6", "Volvo"},
		WMIManufacturer{"4VL", "Volvo"},
		WMIManufacturer{"4VM", "Volvo"},
		WMIManufacturer{"4VZ", "Volvo"},
		WMIManufacturer{"5F", "Honda USA-Alabama"},
		WMIManufacturer{"5L", "Lincoln"},
		WMIManufacturer{"5N1", "Nissan USA"},
		WMIManufacturer{"5NP", "Hyundai USA"},
		WMIManufacturer{"5T", "Toyota USA - trucks"},
		WMIManufacturer{"6AB", "MAN Australia"},
		WMIManufacturer{"6F4", "Nissan Motor Company Australia"},
		WMIManufacturer{"6F5", "Kenworth Australia"},
		WMIManufacturer{"6FP", "Ford Motor Company Australia"},
		WMIManufacturer{"6G1", "General Motors-Holden (post Nov 2002)"},
		WMIManufacturer{"6G2", "Pontiac Australia (GTO & G8)"},
		WMIManufacturer{"6H8", "General Motors-Holden (pre Nov 2002)"},
		WMIManufacturer{"6MM", "Mitsubishi Motors Australia"},
		WMIManufacturer{"6T1", "Toyota Motor Corporation Australia"},
		WMIManufacturer{"6U9", "Privately Imported car in Australia"},
		WMIManufacturer{"8AG", "Chevrolet Argentina"},
		WMIManufacturer{"8GG", "Chevrolet Chile"},
		WMIManufacturer{"8AP", "Fiat Argentina"},
		WMIManufacturer{"8AF", "Ford Motor Company Argentina"},
		WMIManufacturer{"8AD", "Peugeot Argentina"},
		WMIManufacturer{"8GD", "Peugeot Chile"},
		WMIManufacturer{"8A1", "Renault Argentina"},
		WMIManufacturer{"8AK", "Suzuki Argentina"},
		WMIManufacturer{"8AJ", "Toyota Argentina"},
		WMIManufacturer{"8AW", "Volkswagen Argentina"},
		WMIManufacturer{"93U", "Audi Brazil"},
		WMIManufacturer{"9BG", "Chevrolet Brazil"},
		WMIManufacturer{"935", "Citroën Brazil"},
		WMIManufacturer{"9BD", "Fiat Brazil"},
		WMIManufacturer{"9BF", "Ford Motor Company Brazil"},
		WMIManufacturer{"93H", "Honda Brazil"},
		WMIManufacturer{"9BM", "Mercedes-Benz Brazil"},
		WMIManufacturer{"936", "Peugeot Brazil"},
		WMIManufacturer{"93Y", "Renault Brazil"},
		WMIManufacturer{"9BS", "Scania Brazil"},
		WMIManufacturer{"93R", "Toyota Brazil"},
		WMIManufacturer{"9BW", "Volkswagen Brazil"},
		WMIManufacturer{"9FB", "Renault Colombia"},
	}

	manufacturerMap map[string]WMIManufacturer
)

func init() {
	manufacturerMap = make(map[string]WMIManufacturer)

	for _, manuf := range manufacturers {
		manufacturerMap[manuf.code] = manuf
	}
}
